### ISSUE TITLE
Dosbox build broken?

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#124]
e.g. XENON 2 complains about missing `.Phoenicis/engines/wine/dos_support-linux-x86/4.0/bin/dosbox`

see https://github.com/PhoenicisOrg/phoenicis/issues/2230

As I do not know, how the dosbox scripts work, I'm not sure if the issue is in winebuild or the scritps.

In general: should the dosbox build be updated to Wine 5.0.1?

**Comment by Starcommander** [comment]
IMHO: The issue is not in **scripts**, because it is working on mac-os.
- Tested in version alpha2, runs on mac-os, same issue on linux.

By the way: The missing **autoexec.bat** can be ignored.
- Has to do with the **dosbox-wrapper**, that is a bash script.
- In line 88 it is tried to include **drive_c/autoexec.bat** into a new created **autoexec.bat**
- When missing, nothing happens.

The main problem is the missing **dosbox** itself.

An other problem is, that the dosbox-wrapper needs python, just for a simple job: get a simplified directory.
Is this necessary?
Python is not included in flatpak package.

An other question:
Where do you locate the **dosbox scripts** that you mentioned?

**Comment by plata** [comment]
> Just to clarify: scripts=github/PhoenicisOrg/scripts, right?

Yes

> An other problem is, that the dosbox-wrapper needs python, just for a simple job: get a simplified directory.
Is this necessary?
Python is not included in flatpak package.

I don't know. If it is, it should be included in the flatpak package.

> Where do you locate the dosbox scripts that you mentioned?

dosbox scripts = scripts like Xenon 2 which use the dosbox Wine

**Comment by plata** [comment]
@qparis is `dosbox`even supposed to be part of the Wine package?

If I change `dosbox-wrapper` from
```
"$winedir/dosbox" -conf "$tmp_directory/PlayOnLinux_DOSBox.cfg"
```
to
```
"dosbox" -conf "$tmp_directory/PlayOnLinux_DOSBox.cfg"
```
it works.

@Starcommander do you have the `dosbox` application in the bin directory of Wine on OSX?

**Comment by Starcommander** [comment]
On mac **dosbox** is included into **wine**.
I can find it in:
/Users/macuser/Library/Phoenicis/engines/wine/dos_support-darwin-x86/4.0-rc4/bin/dosbox

**Comment by qparis** [comment]
Yes it is supposed to

**Comment by plata** [comment]
@qparis then why is it included for OSX but not for Linux?

**Comment by qparis** [comment]
Probably a bug in winebuild

**Comment by plata** [comment]
Could you check? I don't really know where to look for it.
