### ISSUE TITLE
Build with CFLAGS=-O3 ?

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis-winebuild#16]
It could reduce by a factor 2 or 3 the size of the whole program.

**Comment by qparis** [comment]
Great idea. However, it would also make compilation time longer.  We need to take this into account if we want to provide an on-demand build service

**Comment by ImperatorS79** [comment]
Yes, but the builds will be optimized for speed also.

**Comment by qparis** [comment]
I see! 
Do you think it is possible to imagine a webservice that directly builds a given wine version if the users asks for one instead of storing it? 
We could add a cache on top of this kind service

**Comment by ImperatorS79** [comment]
I think I misspoke, what I meant is that I want wine to be the fastest when executing my .exe, the archives to be the smallest possible when downloading and the wine programs (bin + libs) to take the smallest space on my hard drive. 

Concerning what you have said, since building bi-arch wine take nearly 40 to 60 minutes, I do no think it's possible to do, if I understood correctly what you have said.

**Comment by qparis** [comment]
I don’t know how much time it could take on a server with good hardware

**Comment by plata** [comment]
I agree to @ImperatorS79. Even with great hardware you will probably reach a limit because you cannot build with infinite parallel threads. We should simply run a bot which builds whenever a new version is available.

**Comment by qparis** [comment]
Well, my idea was a kind of mix of this two ideas: 
Let assume that we could compile wine in a reasonable amount of time (10 minutes). Then, instead of compiling *all* the existing versions, we could ask the first user that requires this given version to wait for 10 minutes. After that, the binaries are of course cached and no extra amount of time is required. 

This would allow us to avoid storing very old versions, while keeping maintening support for them.

Same idea with the patch: let say that you are using wine-3.0.2 with a given patch. If tomorrow, wine-3.0.3 is released, you can assume in your scripts that you have wine-3.0.3 with this patch.

**Comment by qparis** [comment]
Don e
