### ISSUE TITLE
Add latest devel/stable/staging version

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#77]
Currently, we must update this information manually in the scripts repo.

**Comment by ImperatorS79** [comment]
@plata Could not we do that by simply analysing the wine json provided by the server ?

**Comment by plata** [comment]
I don't think so. How could we distinguish stable and development?

**Comment by ImperatorS79** [comment]
With the current wine version scheme, stable is always with the pattern y.0.x, with y being currently 4 for example.

**Comment by Gcenx** [comment]
Wine-Stable patter is x.0 / x.0.x (4.0 / 4.0.1)
Wine Devel pattern is x.x / x.x.x (4.12 / 4.12.1)
Wine Release Candidate pattern x.0-rcx (4.0-rc1)

**Comment by plata** [comment]
Is this stated somewhere officially? I.e. can we rely that x.0.x will always be the stable version?

**Comment by ImperatorS79** [comment]
You never know, but I am certain this is the current scheme. Consider it like this: currently you have to update the code every time a new version is out, with my "proposal" you only have to update it if they change the scheme.

**Comment by plata** [comment]
That's true.

**Comment by Gcenx** [comment]
> Is this stated somewhere officially? I.e. can we rely that x.0.x will always be the stable version?

I have never seen anything that 100% confirms this will always be the patten but they haven’t deviated from this since at least Wine-2.0. I could try asking one of my contacts but its only up to one person how releases work.

A x.0.x release has never been anything other then Stable. These have never seen a Staging version
A x.0 release can also be Staging
A x.0-rcx release (Release Candidate) can also be Staging

If they do change the formulae later to could just add an exception to using another ordering from the version the changed happened.

**Comment by plata** [comment]
Ok fine. I think we can try this.

**Comment by plata** [comment]
Nevertheless: wouldn't it make sense to do this computation one and write it to the json instead of doing it for every user every time?

**Comment by plata** [comment]
Not required anymore. See https://github.com/PhoenicisOrg/scripts/pull/1153.
